image: mvdan/fdroid-ci:latest

test:
  script:
    - cd F-Droid
    - ./tools/langs-list-check.py
    - ./tools/check-string-format.py
    - cd ..
    - ./gradlew build
    - ./gradlew checkstyle
    - echo no | android create avd --force -n fcl-test -t android-10 -b armeabi
    - emulator -force-32bit -avd fcl-test -no-skin -no-audio -no-window &
    - ./tools/wait-for-emulator
    - adb shell input keyevent 82
    - ADB_INSTALL_TIMEOUT=8 ./gradlew connectedCheck || { adb logcat -d '*:W'; exit 1; }
    - sed -n 's/.*"ctr2">\([0-9]*\)%<.*/Coverage - \1.0% covered\n/p' F-Droid/build/reports/coverage/debug/index.html
